import Head from "next/head";
import Footer from "@/comps/Footer";
import { Inter } from "next/font/google";
import Nav from "@/comps/Nav";
import Main from "@/comps/Main";
import BackToTop from "../comps/BackToTop"

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Beyaz Takip</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={inter.className}>
        <Nav />
        <Main />
        <Footer />
        <BackToTop/>
      </div>
    </>
  );
}
